### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by surajssd** [neo1691/scorer.py#19]
Traceback (most recent call last):
  File "scorer.py", line 44, in <module>
    r = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='static.cricinfo.com', port=80): Max retries exceeded with url: /rss/livescores.xml (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

**Comment by neo1691** [comment]
I had this same error, Will need to look into it. Thanks for reporting. Let's mark this a low priority bug for now.

**Comment by surajssd** [comment]
Could not find what caused it and also tried to recreate it but didn't come up :confused:

**Comment by neo1691** [comment]
We need to handle it in the code then. And make sure the code does not break when this exception is raised! :)

**Comment by harsham4026** [comment]
@neo1691 PR #54 addresses this issue if the code is not able to reach or resolve the given URL. I believe this code has already been merged into the master. @neo1691 if #54 addressed this issue, you can close it.
